var headerHTML = '<style>'
+'.demotitle{position: absolute;top: 5px;left: 10px;font-size: 24px;font-weight: bold;color: #777;}'
+'#headerInfo{min-width: 320px;	position: absolute;	top: 0px;left: 0px;	height: 75px;z-index: 99999;background-color: rgba(0,0,0,.8);width: 100%;}'
+'a, a:link{color: #999;text-decoration:none;}a:visited { color: #999; }a:hover { color: #ccc; }a:focus { outline: thin dotted; }'
+'a:hover, a:active { outline: 0; }'
+'.links{float: right;opacity: 0.5;}'
+'.navMenu{	color:#C9C9C9;	font-size: 12px;	position: absolute;	bottom: 3px;	right: 15px;}'
+'.links:hover{	opacity: 1;}'
+'</style>'
+'<div ID="headerInfo"><span class="demotitle" id></span>'
+'<div class="links" style="margin:0px; padding:0px;">'
+'<a href= "http://twitter.com/nichom" target="_blank">'
+'<img src="http://nickmartinelli.com/img/twitter-bird-dark-bgs.png" width="30px" style="margin:7px"></a>'
+'</div><nav class="navMenu">'
+'<a href="http://nickmartinelli.com">me</a>&nbsp&nbsp&nbsp/&nbsp&nbsp&nbsp'
+'<a href="http://www.extentpnw.com">blog</a>&nbsp&nbsp&nbsp/&nbsp&nbsp&nbsp'
+'<a href="http://www.pnwmaps.com/neighborhoods">hoods</a>&nbsp&nbsp&nbsp/&nbsp&nbsp&nbsp'
+'<a href="http://nickmartinelli.com/pdxmet">pdx trimet</a>&nbsp&nbsp&nbsp/&nbsp&nbsp&nbsp'
+'<a href="https://www.etsy.com/listing/122152623/portland-bridge-map?">pdx bridges</a></nav></div>';